name: 💬 General Feedback
description: Share thoughts or ideas about the project
labels: ['discussion']
body:
  - type: textarea
    id: feedback
    attributes:
      label: Your feedback
      placeholder: Fire away 🚀
